services:
  typesense:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.typesense
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      typesense:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app/backend:/app/src
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=xyz

  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    depends_on:
      - backend

volumes:
  typesense_data: