# docker-compose.prod.yml
services:
  typesense:
    build:
      context: .
      dockerfile: backend/Dockerfile.typesense.prod
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      - GOTRACEBACK=all # For better debugging
      - TYPESENSE_TIMEOUT_SECONDS=30
    command: >
      sh -c "mkdir -p $${TYPESENSE_DATA_DIR} &&
      echo 'Starting Typesense server...' &&
      /usr/bin/typesense-server
      --data-dir=$${TYPESENSE_DATA_DIR}
      --api-key=$${TYPESENSE_API_KEY}
      --listen-port=8108
      --enable-cors
      --max-memory-ratio=0.8
      --snapshot-interval=120"
    volumes:
        - typesense_data:/data
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1.5'
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8108/health || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 30
      start_period: 30s #initial grace period
    networks:
      - app-network
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - ENV=production
      - DEBUG=false
      - PYTHONPATH=/app/src
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - STARTUP_DELAY=15
      - TYPESENSE_TIMEOUT_SECONDS=30
    volumes:
      - /home/deploy/app/.env:/app/.env:ro  # Mount the env file
      - static_volume:/app/src/static # Mount static files
    user: "myuser"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10  # Increased from 3
      start_period: 60s  # Increased grace period
    command: >
      sh -c "echo 'Waiting $${STARTUP_DELAY}s for dependencies...';
      sleep $${STARTUP_DELAY};
      echo 'Starting Uvicorn...';
      uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --no-access-log;
      echo 'Uvicorn exited with status $?'"
    depends_on:
      typesense:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend  # Fixed path (was .frontend)
      dockerfile: Dockerfile.prod
    environment:
      - ENV=production
      - BACKEND_URL=https://${DOMAIN}  # Changed from PROD_DOMAIN to DOMAIN
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/config/dhparam:/etc/nginx/dhparam:ro
      - static_volume:/var/www/static
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    entrypoint: ""
    command: >
      sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot;
      sleep 12h & wait $$!;
      done"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  typesense_data:
    driver: local
    driver_opts:
      type: none
      device: /home/deploy/app_data/typesense
      o: bind
  static_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/deploy/app_data/static
      o: bind
  certbot_www:
  certbot_conf:

networks:
  app-network:
    driver: bridge
