# docker-compose.override.yml
services:
  # Backend Test Service - Development only
  backend-tests:
    profiles: ["development"]  # Only included in dev environment
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-tests
    volumes:
      - ./backend/src:/app/src  # Source code
      - ./backend/tests:/app/tests  # Test files
    environment:
      - TEST_ENV=development  # Test-specific environment
      - TYPESENSE_API_KEY=${TEST_TYPESENSE_API_KEY:-test_key}  # Test API key
      - TYPESENSE_STARTUP_WAIT_SECONDS=5
    depends_on:
      typesense:
        condition: service_healthy
      backend:
        condition: service_healthy
    command: ["./run_tests.sh"]  # Custom test runner
    networks:
      app-network:
        aliases:
          - backend-tests

  # Frontend Test Service - Development only
  frontend-tests:
    profiles: ["development"]
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-tests
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/tests:/app/tests
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    command: ["./run_tests.sh"]
    networks:
      app-network:
        aliases:
          - frontend-tests
