# docker-compose.yml
services:
  # Typesense Search Service - Used in both development and production
  typesense:
    build:
      context: .  # Build from project root
      dockerfile: backend/Dockerfile.typesense  # Custom Typesense Dockerfile
    container_name: typesense-db  # Explicit container naming
    ports:
      - "${TYPESENSE_PORT}:8108"  # Map configured port to default Typesense port
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}  # Authentication key
      - TYPESENSE_DATA_DIR=${TYPESENSE_DATA_DIR}  # Persistent data location
    volumes:
      - typesense_data:/data  # Named volume for search data persistence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]  # Health endpoint
      interval: 10s  # Check every 10 seconds
      timeout: 5s  # Fail if no response in 5s
      retries: ${TYPESENSE_HEALTHCHECK_RETRIES:-10}  # Configurable retries
    networks:
      - app-network  # Connect to application network

  # Backend API Service - Base configuration
  backend:
    build:
      context: .  # Build from project root
      dockerfile: backend/Dockerfile  # Backend-specific Dockerfile
    container_name: backend-app  # Explicit container naming
    ports:
      - "${BACKEND_PORT}:8000"  # Map configured port to default backend port
    environment:
      # Environment configuration with defaults
      - ENV=${ENV:-development}  # dev/prod environment
      - DEBUG=${DEBUG:-true}  # Debug mode
      - PYTHONPATH=${BACKEND_PYTHONPATH:-/app/src}  # Python module path
      # Typesense connection parameters
      - TYPESENSE_HOST=${TYPESENSE_HOST}
      - TYPESENSE_PORT=${TYPESENSE_PORT}
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      # Application parameters
      - BACKEND_PORT=${BACKEND_PORT}
      - TYPESENSE_PROTOCOL=${TYPESENSE_PROTOCOL:-http}  # Default to HTTP
      # Healthcheck and timeout parameters
      - BACKEND_STARTUP_DELAY=${BACKEND_STARTUP_DELAY:-10}
      - TYPESENSE_CONNECTION_TIMEOUT=${TYPESENSE_CONNECTION_TIMEOUT:-30}
    volumes:
      # Development mounts - overridden in production
      - ./backend/src:/app/src  # Source code mount
      - ./backend/static:/app/static  # Static files mount
    depends_on:
      typesense:
        condition: service_healthy  # Wait for healthy Typesense
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_PORT}/health || exit 1"]
      interval: 30s
      timeout: ${TYPESENSE_CONNECTION_TIMEOUT:-30}s
      retries: ${TYPESENSE_HEALTHCHECK_RETRIES:-5}
    networks:
      - app-network

  # Frontend Web Service - Base configuration
  frontend:
    build:
      context: .  # Build from project root
      dockerfile: frontend/Dockerfile  # Frontend-specific Dockerfile
    container_name: frontend-app  # Explicit container naming
    ports:
      - "${FRONTEND_PORT}:8001"  # Map configured port to default frontend port
    environment:
      # Environment configuration with defaults
      - ENV=${ENV:-development}
      - PYTHONPATH=${FRONTEND_PYTHONPATH:-/app}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_URL=${BACKEND_URL:-http://backend:8000}  # Default backend URL
    volumes:
      - ./frontend/src:/app/src  # Source code mount
      - ./frontend/src/app/static:/app/src/app/static  # Explicit static files mount
    depends_on:
      - backend  # Requires backend to be available
    networks:
      - app-network

# Network configuration
networks:
  app-network:
    driver: bridge  # Default bridge network for inter-container communication

# Volume declarations
volumes:
  typesense_data:  # Persistent storage for Typesense
    driver: local