services:
  typesense:
    build:
      context: ./backend
      dockerfile: Dockerfile.typesense
    container_name: typesense-db
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - PYTHONPATH=/app/backend:/app/src
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=xyz
    depends_on:
      typesense:
        condition: service_healthy

  # Add a service for running tests
  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-tests
    depends_on:
      - backend
      - typesense
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    command: pytest tests/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "8001:8001"
    depends_on:
      - backend

volumes:
  typesense_data: