services:
  typesense:
    image: typesense/typesense:0.24.1
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - typesense

  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    depends_on:
      - backend

volumes:
  typesense_data: